"""URLs for the custom admin / manage area (not Django admin)."""
from django.urls import path
from . import views_manage

app_name = 'manage'

urlpatterns = [
    path('', views_manage.dashboard, name='dashboard'),
    path('members/', views_manage.members_list, name='members'),
    path('members/<int:pk>/approve/', views_manage.member_approve, name='member_approve'),
    path('members/<int:pk>/reject/', views_manage.member_reject, name='member_reject'),
    path('donors/', views_manage.donors_list, name='donors'),
    path('donors/<int:pk>/approve/', views_manage.donor_approve, name='donor_approve'),
    path('county-officials/', views_manage.county_officials_list, name='county_officials'),
    path('county-officials/<int:pk>/verify/', views_manage.county_official_verify, name='county_official_verify'),
    path('users/', views_manage.users_list, name='users_list'),
    path('users/add/', views_manage.user_add, name='user_add'),
    path('users/<int:pk>/edit/', views_manage.user_edit, name='user_edit'),
    path('gallery/', views_manage.gallery_list, name='gallery_list'),
    path('gallery/add/', views_manage.gallery_add, name='gallery_add'),
    path('gallery/<int:pk>/edit/', views_manage.gallery_edit, name='gallery_edit'),
    path('gallery/<int:pk>/delete/', views_manage.gallery_delete, name='gallery_delete'),
    path('projects/', views_manage.projects_list, name='projects_list'),
    path('projects/add/', views_manage.project_add, name='project_add'),
    path('projects/<int:pk>/edit/', views_manage.project_edit, name='project_edit'),
    path('projects/<int:pk>/delete/', views_manage.project_delete, name='project_delete'),
    path('events/', views_manage.events_list, name='events_list'),
    path('events/add/', views_manage.event_add, name='event_add'),
    path('events/<int:pk>/edit/', views_manage.event_edit, name='event_edit'),
    path('events/<int:pk>/delete/', views_manage.event_delete, name='event_delete'),
    path('sports/programs/', views_manage.sport_programs_list, name='sport_programs_list'),
    path('sports/programs/add/', views_manage.sport_program_add, name='sport_program_add'),
    path('sports/programs/<int:pk>/edit/', views_manage.sport_program_edit, name='sport_program_edit'),
    path('sports/programs/<int:pk>/delete/', views_manage.sport_program_delete, name='sport_program_delete'),
    path('sports/teams/', views_manage.teams_list, name='teams_list'),
    path('sports/teams/add/', views_manage.team_add, name='team_add'),
    path('sports/teams/<int:pk>/edit/', views_manage.team_edit, name='team_edit'),
    path('sports/teams/<int:pk>/delete/', views_manage.team_delete, name='team_delete'),
    path('about/', views_manage.about_edit, name='about_edit'),
    path('officials/', views_manage.officials_list, name='officials_list'),
    path('officials/add/', views_manage.official_add, name='official_add'),
    path('officials/<int:pk>/edit/', views_manage.official_edit, name='official_edit'),
    path('officials/<int:pk>/delete/', views_manage.official_delete, name='official_delete'),
    path('youth-jobs/', views_manage.youth_jobs_list, name='youth_jobs_list'),
    path('youth-jobs/add/', views_manage.youth_job_add, name='youth_job_add'),
    path('youth-jobs/<int:pk>/edit/', views_manage.youth_job_edit, name='youth_job_edit'),
    path('youth-jobs/<int:pk>/delete/', views_manage.youth_job_delete, name='youth_job_delete'),
    path('section-backgrounds/', views_manage.section_styles_list, name='section_styles_list'),
    path('section-backgrounds/add/', views_manage.section_style_add, name='section_style_add'),
    path('section-backgrounds/<int:pk>/edit/', views_manage.section_style_edit, name='section_style_edit'),
    path('section-backgrounds/<int:pk>/delete/', views_manage.section_style_delete, name='section_style_delete'),
    path('section-backgrounds/<int:section_pk>/slides/add/', views_manage.section_slide_add, name='section_slide_add'),
    path('section-slides/<int:pk>/delete/', views_manage.section_slide_delete, name='section_slide_delete'),
    path('settings/', views_manage.settings_edit, name='settings'),
    path('messages/', views_manage.contact_messages, name='messages'),
]
