# Generated by Django 5.0.1 on 2026-01-28 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('reply_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('member_participation', 'Member Participation'), ('project_progress', 'Project Progress'), ('funding_allocation', 'Funding Allocation'), ('financial', 'Financial'), ('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('report_file', models.FileField(upload_to='reports/')),
                ('report_url', models.URLField(blank=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('report_date', models.DateField()),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='projects.project')),
            ],
            options={
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['report_type', '-report_date'], name='reports_rep_report__f2cd1a_idx'), models.Index(fields=['project', '-report_date'], name='reports_rep_project_e2e462_idx')],
            },
        ),
    ]
