# Generated by Django 5.2.10 on 2026-02-09 22:37

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_galleryitem_file_optional_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='file',
            field=models.FileField(blank=True, help_text='Upload an image/video file', null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/pc/CBO/backend/media')), upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/pc/CBO/backend/media')), upload_to='gallery/thumbnails/'),
        ),
    ]
