# Generated by Django 5.0.1 on 2026-01-28 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funding', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='projects.project'),
        ),
        migrations.AddField(
            model_name='donationtier',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_tiers', to='projects.project'),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.county'),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.ministry'),
        ),
        migrations.AddField(
            model_name='donation',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='funding.sponsor'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status', '-created_at'], name='funding_don_status_cb9952_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['project', 'status'], name='funding_don_project_d640ad_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['transaction_id'], name='funding_don_transac_8c4417_idx'),
        ),
    ]
