# Generated by Django 5.2.10 on 2026-02-09 22:37

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingsource',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/pc/CBO/backend/media')), upload_to='funding_sources/'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/pc/CBO/backend/media')), upload_to='sponsors/'),
        ),
    ]
