# Generated by Django 5.0.1 on 2026-01-28 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('gamification', '0001_initial'),
        ('members', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='members.memberprofile'),
        ),
        migrations.AddField(
            model_name='memberbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_badges', to='gamification.badge'),
        ),
        migrations.AddField(
            model_name='memberbadge',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_badges', to='members.memberprofile'),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event'),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to='members.memberprofile'),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['year', 'month', 'rank'], name='gamificatio_year_8b8c0e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboard',
            unique_together={('year', 'month', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='memberbadge',
            unique_together={('member', 'badge')},
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['member', '-created_at'], name='gamificatio_member__21cfc9_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='gamificatio_transac_bab136_idx'),
        ),
    ]
