# Generated by Django 5.2.10 on 2026-02-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, default='Empowering youth, transforming communities', max_length=300)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('our_story', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About page content',
                'verbose_name_plural': 'About page content',
            },
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(help_text='e.g. Chairperson, Treasurer, Secretary', max_length=120)),
                ('bio', models.TextField(blank=True, help_text='Short bio or role description (optional)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='officials/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower first)')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Officials',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='YouthJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('organization', models.CharField(blank=True, help_text='Employer or organization name', max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('apply_url', models.URLField(blank=True, help_text='Link to apply or more info')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=25)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Youth jobs / opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hotline_2',
            field=models.CharField(blank=True, default='+254728758157', max_length=25),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hotline_3',
            field=models.CharField(blank=True, default='+254787786299', max_length=25),
        ),
    ]
