# Generated by Django 5.2.10 on 2026-02-09 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_officials_youth_jobs_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(help_text='e.g. header, hero, about_hero, contact_hero, footer. Used in templates.', max_length=60, unique=True)),
                ('label', models.CharField(help_text='Display name in admin (e.g. Header, Home Hero)', max_length=120)),
                ('background_type', models.CharField(choices=[('plain', 'Plain (solid color)'), ('image', 'Single image'), ('video', 'Video (upload or URL)'), ('carousel', 'Image carousel / slides'), ('auto_slides', 'Automatic sliding carousel')], default='plain', max_length=20)),
                ('background_color', models.CharField(blank=True, default='#ffffff', max_length=20)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='sections/')),
                ('background_video', models.FileField(blank=True, null=True, upload_to='sections/video/')),
                ('background_video_url', models.URLField(blank=True, help_text='Or use YouTube/Vimeo URL instead of upload')),
                ('slide_interval_seconds', models.PositiveSmallIntegerField(default=5, help_text='For carousel/auto_slides')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section background',
                'verbose_name_plural': 'Section backgrounds',
                'ordering': ['section_key'],
            },
        ),
        migrations.CreateModel(
            name='SectionSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sections/slides/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('section_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='core.sectionstyle')),
            ],
            options={
                'ordering': ['section_style', 'order'],
            },
        ),
    ]
