# Generated by Django 5.2.10 on 2026-02-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_section_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company / organization name (for donors)', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('administration', 'Administration & Public Service'), ('agriculture', 'Agriculture, Livestock & Irrigation'), ('education', 'Education, Gender, Culture & Social Services'), ('finance', 'Finance, ICT & Economic Planning'), ('health', 'Health Services'), ('land', 'Land, Housing, Physical Planning & Urban Development'), ('roads', 'Roads, Transport & Public Works'), ('trade', 'Trade, Industrialization, Tourism and Investment'), ('water', 'Water, Environment, Natural Resources and Climate Change'), ('youth', 'Youth Affairs, Sports & Communication')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('public', 'Public User'), ('member', 'Member'), ('donor', 'Donor / Sponsor'), ('county_official', 'County Official'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='public', max_length=20),
        ),
    ]
