# Generated by Django 5.2.10 on 2026-02-09 22:37

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_kiambu_constituencies_wards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('verify', 'Verify')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sectionslide',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/pc/CBO/backend/media')), upload_to='sections/slides/'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='background_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/pc/CBO/backend/media')), upload_to='sections/'),
        ),
        migrations.AlterField(
            model_name='sectionstyle',
            name='background_video',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/pc/CBO/backend/media')), upload_to='sections/video/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, default="Gikambura (BUJU), Karai Ward, Youth Labour Office, Just Besides MCA's Office Along Gikambura Stadium"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/pc/CBO/backend/media')), upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Organization logo (header)', null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/pc/CBO/backend/media')), upload_to='site/'),
        ),
    ]
